services:
  # Tracing of domain events
  Biig\Component\Domain\Event\DomainEventDispatcherTracer:
    arguments:
      - '@Biig\Component\Domain\Event\DomainEventDispatcherTracer.inner'
    decorates: Biig\Component\Domain\Event\DomainEventDispatcher

  Biig\Component\Domain\Integration\Symfony\Twig\Profiler\EventsDataCollector:
    arguments:
      - '@Biig\Component\Domain\Event\DomainEventDispatcherTracer'
    tags:
      - name:     data_collector
        # TODO Need to register DomainBundle to twig namespace ?
        template: '@DomainBundle/data_collector/events_dispatched.html.twig'
        id:       'biig.domain_events'
